### ISSUE TITLE
ImportError: No module named 'IPython'

### ISSUE THREAD

**Issue by createnewli** [chenjiandongx/pyecharts#102]
Win10 Python 3.5.2
卸载了原本安装的0.1.5版本后重新安装会报没有Ipython，安装IPython后会继续提示没有ipython.html.nbextensions，这个无法继续安装了

![image](https://user-images.githubusercontent.com/20616294/29398048-c1f7e536-8354-11e7-8250-908a0c1eb5c8.png)

**Comment by chfw** [comment]
Would you like to try jupyter-notebook instead while we try to see what's wrong with ipython?

**Comment by chenjiandongx** [comment]
@createnewli 
安装 notebook 可以解决问题 pip install notebook

然后再次安装 pyecharts pip install pyecharts

**Comment by chfw** [comment]
http://ipython.org/news.html#ipython-4-0

For 4.0, we will split up components into several packages. The parts which work for any language will be called Jupyter, while the parts specific to executing Python code will remain as IPython.

**Comment by createnewli** [comment]
嗯，安装Jupyter notebook后可以正常安装了

**Comment by chfw** [comment]
Once jupyter-pip will be released, this problem will go away. But for now, please install notebook before the installation of pyecharts.

And the implications are:

Before the installation of pyecharts, in your environment/virtual environment
1) if you do not have jupyter/ipython, the installation of pyecharts will succeed without the installation of juypter nbextensions. It means if you get jupyter notebook later, you need to re-install pyecharts in order to get its jupyter support

2) if you already have jupyter/ipython, you have nothing to worry about. All would work as expected.

**Comment by chfw** [comment]
New jupyter-pip is released. Please try again. You shall not have any problems. Even the user do not have jupypter/ipython, the installation shall proceed. For example, if you are django/flask developer, you won't have any problems.

![image](https://user-images.githubusercontent.com/4280312/29464420-c2081f76-842d-11e7-8f7e-713bf6637641.png)

**Comment by chenjiandongx** [comment]
请及时更新到新版本
